source 'https://rubygems.org'

gem "activesupport", ">= 6.0.3.1"
gem "nokogiri"
gem "jekyll"
gem "jekyll-paginate-v2"
gem "jekyll-archives"
gem "jekyll-redirect-from"
gem "jekyll-seo-tag"
gem "jekyll-avatar"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-include-cache"
gem "jemoji"
gem "jekyll-mentions"
gem "minimal-mistakes-jekyll"